---
# tasks file for kubeadm

# https://gist.github.com/alexellis/fdbc90de7691a1b9edb545c17da2d975
- name: Disable Swap
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  ignore_errors: True

# Docker Convenience Script Can Only Be Run Once
- name: Determine if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_there
  ignore_errors: True

# https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script
- name: Run Docker {{ docker_ce_version }} Install Script
  environment:
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1
  script: "files/get-docker.sh {{ docker_ce_version }}"
  when: docker_there.stat.exists == False
  register: docker_installed

- name: Lock docker version to {{ docker_ce_version}}
  command: /usr/bin/apt-mark hold docker-ce
  when: docker_installed.changed

- name: Pass bridged IPv4 traffic to iptables' chains
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

# https://kubernetes.io/docs/setup/independent/install-kubeadm/
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: Add Google Cloud Repo Key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  args:
    warn: no

- name: Add Kubernetes to Available apt Sources
  template:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: 0644

- name: Install k8s {{ kubernetes_package_version }} Y'all
  apt:
    name: "{{ item }}={{ kubernetes_package_version }}"
    state: present
    force: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
