---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  register: hostname
  tags: hostname

- name: set timezone to UTC
  timezone:
    name: UTC
  register: timezone

# - name: gpu mem check
#   shell: cat /boot/config.txt | grep gpu_mem
#   changed_when: false
#   register: gpu_mem_check

# - name: reduce gpu memory
#   lineinfile:
#     path: /boot/config.txt
#     line: gpu_mem=16
#   register: gpu_mem
#   when: gpu_mem_check.stdout == ""

- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

# - name: Create a directory if it does not exist
#   file:
#     path: /etc/docker
#     state: directory
#     mode: '0755'

# - name: Setting docker daemon.json
#   copy:
#     src: daemon.json
#     dest: /etc/docker/daemon.json
#     owner: root
#     group: root
#     mode: 0755
#   register: dockerdaemon
#   tags:
#     - dockerdaemon

# Doc: http://manpages.ubuntu.com/manpages/trusty/man8/dphys-swapfile.8.html
- name: Disable Swap
  lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: CONF_SWAPSIZE=0
  register: swap

- name: apt-get update
  apt:
    update_cache: 'yes'
    autoclean: 'yes'
    autoremove: 'yes'
    cache_valid_time: 86400
    upgrade: 'yes'

- name: python-apt dependency
  apt:
    name: ['python-apt']
    state: present

- name: Reboot
  reboot:
    reboot_timeout: 120
  when: cmdline.changed or timezone.changed or hostname.changed or swap.changed
