---
- name: Ensure hostname set
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')
  tags:
    - hostname

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^{{ ansible_default_ipv4.address }}.+$"
    line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  tags:
    - hostname

# tasks file for common
- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

- name: Pass bridged IPv4 traffic to iptables' chains
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: apt-get update
  apt:
    update_cache=yes
    autoclean=yes
    autoremove=yes
    cache_valid_time=86400

- name: apt-get upgrade
  apt:
    upgrade=full

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot for /boot/cmdline.txt Change"
  async: 1
  poll: 0
  ignore_errors: True
  when: cmdline|changed
  tags:
    - boot
    - shutdown

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 15
    timeout: 90
  become: False
  when: cmdline|changed
  tags:
    - boot
    - shutdown